const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={api:false,csrfToken:'',caseId:null,sampleId:null,cases:[],samples:[],jobs:[],evidence:[],reports:[],audit:[],messages:[],toolchain:{},page:0,filter:'',drafts:new Map(),layouts:new Map(),busy:new Set(),epoch:0,settings:null};
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),5000)};
const put=(s,t)=>{if($(s))$(s).textContent=t},html=(s,t)=>{if($(s))$(s).innerHTML=t};
const inCase=x=>x.case_id===state.caseId,when=x=>x?new Date(x).toLocaleString():'未记录',provenance=x=>x.demo?'演示记录':x.source||x.hash_source||'用户登记';
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(state.csrfToken?{'X-ReverseAI-Token':state.csrfToken}:{}),...options.headers}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`API ${r.status}`);return r.json()}
const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
async function action(key,fn){if(state.busy.has(key))return;state.busy.add(key);try{await fn()}catch(e){toast(e.message)}finally{state.busy.delete(key)}}
const navigation=[];let currentView='overview';
function view(id,back=false){if(id!==currentView&&!back)navigation.push(currentView);currentView=id;$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));put('#title',id==='overview'?'总览':$(`#${id} h1`)?.textContent||'总览');if(id==='evidence')requestAnimationFrame(renderGraph);if(['settings','knowledge','apiSettings','mcpSettings','skillSettings','agentSettings'].includes(id))loadSettings()}
function selectedSample(){return state.samples.find(x=>inCase(x)&&x.id===state.sampleId)||state.samples.find(inCase)||null}
function rememberDrafts(){$$('[data-review-note]').forEach(n=>state.drafts.set(`${state.caseId}/${n.dataset.reviewNote}`,n.value))}
function renderSamples(){const items=state.samples.filter(inCase);const rows=items.map(s=>`<tr><td><b>${escapeHTML(s.name)}</b><small>${escapeHTML(s.id)}<br>SHA-256（${s.stored_apk?'服务端校验':'客户端声明'}）：${escapeHTML(s.sha256)}</small></td><td>${escapeHTML(s.kind)}</td><td>${escapeHTML(provenance(s))} · 未评估</td><td>${when(s.created_at)}<br><button data-sample="${escapeHTML(s.id)}">${s.id===state.sampleId?'已选择':'选择'}</button></td></tr>`).join('')||'<tr><td colspan="4">当前 Case 暂无样本</td></tr>';html('#sampleRows',rows);html('#libraryRows',rows);put('#metricSamples',items.length);put('#navSampleCount',items.length)}
function jobCard(j){
 const result=j.result,verification=result?.verification;
 const artifacts=(j.artifacts||[]).map(name=>`<li><a href="/api/apk/jobs/${encodeURIComponent(j.id)}/artifact?case_id=${encodeURIComponent(j.case_id)}&amp;name=${encodeURIComponent(name)}" target="_blank" rel="noopener">${escapeHTML(name)}</a></li>`).join('');
 return `<article><label>${escapeHTML(j.type)} · ${escapeHTML(j.status)}</label><b>${escapeHTML(state.samples.find(s=>s.id===j.sample_id)?.name||j.sample_id)}</b><p>${escapeHTML(j.reason||'未记录原因')}</p>${j.executor==='apk_static/v1'?`<p>模型：${escapeHTML(j.model)} · 静态分析，未执行样本</p><progress max="100" value="${Number(j.progress)||0}" aria-label="分析进度"></progress>`:''}<small>${escapeHTML(j.id)}<br>Case: ${escapeHTML(j.case_id)}<br>${escapeHTML(provenance(j))} · ${when(j.created_at)}</small>${verification?.candidate?`<p>候选答案：${escapeHTML(verification.candidate)}</p><p>推导重放：${verification.derivation_replayed?'通过':'未验证'}；OCR 匹配：${verification.candidate_in_derived_ocr?'通过':'未验证'}。仍需人工复核。</p>`:''}${result?.attempts?.length?`<details><summary>调用记录（${result.attempts.length}）</summary><pre>${escapeHTML(JSON.stringify(result.attempts,null,2))}</pre></details>`:''}${artifacts?`<details><summary>下载证据与派生产物</summary><ul>${artifacts}</ul></details>`:''}${j.evidence_id?`<p>输出证据：${escapeHTML(j.evidence_id)}</p>`:''}${(['blocked','queued'].includes(j.status)||(j.status==='running'&&j.executor==='apk_static/v1'))?`<button data-cancel-job="${escapeHTML(j.id)}">取消任务</button>`:''}</article>`;
}

function renderJobs(){const allJobs=state.jobs.filter(inCase).filter(j=>j.type!=='agent_child'),jobs=allJobs.filter(j=>j.type!=='agent_parent');for(const key of ['running','review','done']){const col=$(`[data-kanban="${key}"]`);if(!col)continue;const items=jobs.filter(j=>(['completed','done','cancelled','failed'].includes(j.status)?'done':['blocked','needs_review'].includes(j.status)?'review':'running')===key);const head=col.querySelector('h3');col.innerHTML=(head?.outerHTML||'<h3><small></small></h3>')+(items.map(jobCard).join('')||'<article>暂无任务</article>');col.querySelector('h3 small').textContent=items.length}put('#metricJobs',allJobs.filter(j=>['queued','running'].includes(j.status)).length);put('#navJobCount',allJobs.length)}
function renderEvidence(){rememberDrafts();const items=state.evidence.filter(inCase),reviewed=items.filter(x=>['accepted','rejected'].includes(x.status)).length,progress=items.length?Math.round(reviewed/items.length*100):0;html('#metricEvidence',`${progress}<small>%</small>`);const bar=$('.progress i');if(bar){bar.style.width=`${progress}%`;bar.parentElement.setAttribute('aria-label',`已复核 ${progress}%`)}put('#metricFindings',items.filter(x=>x.status==='needs_review').length);put('#metricHighRisk',0);const filtered=items.filter(x=>!state.filter||x.status===state.filter);state.page=Math.min(state.page,Math.max(0,Math.ceil(filtered.length/20)-1));html('#evidenceList',filtered.slice(state.page*20,state.page*20+20).map(e=>`<article class="evidence-item"><header><b>${escapeHTML(e.subject)}</b><mark>${escapeHTML(e.status)}</mark></header><p>${escapeHTML(e.claim)}</p><small>${escapeHTML(e.id)} · ${escapeHTML(provenance(e))} · ${when(e.created_at)} · ${e.confidence==null?'未评分':escapeHTML(e.confidence)}</small><p>样本：${escapeHTML(e.sample_id)}</p><button data-record="${escapeHTML(e.id)}">查看原始记录 / 图中定位</button>${e.status==='needs_review'?`<textarea data-review-note="${escapeHTML(e.id)}" aria-label="复核备注" placeholder="人工复核备注（必填）">${escapeHTML(state.drafts.get(`${state.caseId}/${e.id}`)||'')}</textarea><div class="review-actions"><button data-review="accepted" data-id="${escapeHTML(e.id)}">接受</button><button data-review="rejected" data-id="${escapeHTML(e.id)}">拒绝</button></div>`:`<p>复核备注：${escapeHTML(e.review_note||'未记录')} · ${when(e.reviewed_at)}</p>`}</article>`).join('')||'<p>当前筛选下暂无证据。</p>');put('#evidencePage',`${state.page+1} / ${Math.max(1,Math.ceil(filtered.length/20))} 页 · ${filtered.length} 条`);if($('#evidencePrev'))$('#evidencePrev').disabled=state.page===0;if($('#evidenceNext'))$('#evidenceNext').disabled=(state.page+1)*20>=filtered.length;renderGraph()}
function renderToolchain(){
  const label=item=>!state.api?'状态未知':item?.status==='connected'?'桥 / 服务测试成功':item?.status==='configured'?'已配置 / 待测试':'未配置';
  for(const [name,prefix] of [['ghidra_mcp','ghidra'],['frida','frida']]){const item=state.toolchain[name];put(`#${prefix}Status`,label(item));put(`#${prefix}Meta`,state.api?item?.reason||'未配置':'API 离线，无法读取当前状态')}
  const names=['ghidra_mcp','frida','sandbox'];$$('.health strong').forEach((node,i)=>node.textContent=label(state.toolchain[names[i]]));put('.health b',state.api?'本地状态':'离线');
}
function renderActivity(){const records=state.audit.filter(inCase).slice().reverse();html('#auditList',records.map(x=>`<article class="evidence-item"><b>${escapeHTML(x.action)}</b><p>${escapeHTML(x.target)}</p><small>${when(x.created_at)} · ${escapeHTML(x.id)}</small></article>`).join('')||'<p>当前 Case 暂无审计事件。</p>');html('.feed',records.slice(0,5).map(x=>`<div><p><b>${escapeHTML(x.action)}</b><small>${when(x.created_at)}</small><label>${escapeHTML(x.target)}</label></p></div>`).join('')||'<p>暂无活动</p>')}
function renderMessages(){html('#messages',state.messages.filter(inCase).map(m=>`<div class="msg ${m.role==='user'?'user':'ai'}"><div><p>${escapeHTML(m.content)}</p><small>${when(m.created_at)} · ${m.mode==='provider'?escapeHTML(m.provider)+' / '+escapeHTML(m.model):'本地规则 / 非 LLM'}</small></div></div>`).join('')||'<p>当前 Case 暂无对话。本地规则助手不会调用 LLM 或分析文件。</p>')}
function renderReports(){html('#reportList',state.reports.filter(inCase).map(r=>`<article class="evidence-item"><b>${escapeHTML(r.id)} · ${escapeHTML(r.format)}</b><p>${when(r.created_at)} · 当前 Case 证据冻结快照（含演示标记）</p><small>SHA-256：${escapeHTML(r.sha256||'旧版记录，无快照校验信息')}</small><button data-download="${escapeHTML(r.id)}">下载已生成报告</button></article>`).join('')||'<p>尚无报告记录</p>')}
function renderAll(){const s=selectedSample();put('#contextSample',s?.name||'未选择样本');put('#contextMeta',s?`${provenance(s)} · ${s.stored_apk?'APK 已上传并校验哈希':'类型为客户端声明'} · 未评估`:'等待元数据');html('#caseSelect',state.cases.map(x=>`<option value="${escapeHTML(x.id)}" ${x.id===state.caseId?'selected':''}>${escapeHTML(x.name)}</option>`).join(''));renderSamples();renderJobs();renderEvidence();renderToolchain();renderActivity();renderMessages();renderReports();if(typeof renderAgentJobs==='function')renderAgentJobs()}
async function refreshDataNow(){const epoch=++state.epoch;try{const health=await api('/api/health');state.csrfToken=health.csrf_token;const cases=await api('/api/cases');if(epoch!==state.epoch)return;const id=cases.items.some(x=>x.id===state.caseId)?state.caseId:cases.items[0]?.id||null;const [samples,jobs,toolchain,reports,audit,messages,evidence]=await Promise.all([...['/api/samples','/api/analysis/jobs','/api/toolchain/health','/api/reports','/api/audit','/api/messages'].map(p=>api(p)),id?api(`/api/evidence/${encodeURIComponent(id)}`):Promise.resolve({items:[]})]);if(epoch!==state.epoch)return;Object.assign(state,{api:true,caseId:id,cases:cases.items,samples:samples.items,jobs:jobs.items,toolchain:toolchain.items,reports:reports.items,audit:audit.items,messages:messages.items,evidence:evidence.items});state.sampleId=selectedSample()?.id||null;renderAll();put('.sync',`已同步 · ${new Date().toLocaleTimeString()}`)}catch(e){if(epoch!==state.epoch)return;state.api=false;put('.sync',`离线 · 显示上次数据：${e.message}`);renderToolchain()}}
let refreshPending=null;
function refreshData(){
  if(refreshPending)return refreshPending;
  refreshPending=refreshDataNow().finally(()=>{refreshPending=null});
  return refreshPending;
}
async function sha256(file){if(!window.crypto?.subtle)throw new Error('当前浏览器不支持安全 SHA-256');return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function registerSamples(list){
 if(!state.api||!state.caseId){toast('请连接 API 并选择 Case');return}
 const caseId=state.caseId;
 await action('import',async()=>{
  let uploaded=0;
  for(const file of list){
   const apk=/\.apk(?:\.bin)?$/i.test(file.name);
   if(apk&&file.size>100000000)throw new Error('APK 文件不能超过 100 MB');
   const r=apk?await api(`/api/samples/apk?case_id=${encodeURIComponent(caseId)}&name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/vnd.android.package-archive'},body:file}):await post('/api/samples',{case_id:caseId,name:file.name,size:file.size,mime:file.type||'application/octet-stream',sha256:await sha256(file),kind:'Unknown'});
   if(apk)uploaded++;
   if(state.caseId===caseId)state.sampleId=r.sample.id;
  }
  await refreshData();toast(uploaded?'APK 已上传并校验哈希，可启动静态分析；其他文件仅登记元数据':'已登记元数据；未上传文件正文');view('samples');
 });
}
async function start(type='ai_orchestrator'){
 if(!state.api||!selectedSample()){toast('请连接 API 并选择当前 Case 样本');return}
 await action('job',async()=>{
  const sample=selectedSample(),apk=type==='android_analysis'||(type==='ai_orchestrator'&&sample.stored_apk);
  if(apk&&!sample.stored_apk)throw new Error('请先导入 APK 文件正文');
  const payload={case_id:state.caseId,sample_id:sample.id,type};
  if(apk){const model=$('#apkModel')?.value.trim();if(model)payload.model=model;payload.max_calls=Number($('#apkCalls')?.value||12);payload.seconds=900;payload.task=$('#apkTask')?.value.trim()||''}
  const j=await post(apk?'/api/apk/jobs':'/api/analysis/jobs',payload);
  await refreshData();toast(j.reason);view('analysis');
 });
}

function openEditor(title,fields,save){const dialog=$('#editor');put('#editorTitle',title);html('#editorFields',fields);put('#editorError','');$('#editorSave').hidden=!save;$('#editorSave').disabled=false;$('#editorCancel').disabled=false;$('#editorForm').onsubmit=async e=>{e.preventDefault();if(!save||$('#editorSave').disabled)return;$('#editorSave').disabled=true;$('#editorCancel').disabled=true;try{await save(new FormData(e.target));dialog.close();html('#editorFields','')}catch(error){put('#editorError',error.message)}finally{$('#editorSave').disabled=false;$('#editorCancel').disabled=false}};dialog.showModal()}
const field=(name,label,value='',multi=false)=>`<label>${label}${multi?`<textarea name="${name}" required>${escapeHTML(value)}</textarea>`:`<input name="${name}" value="${escapeHTML(value)}" required>`}</label>`;
function newCase(){openEditor('新建 Case',field('name','工作区名称')+field('authorization','授权范围说明','',true),async form=>{const c=await post('/api/cases',Object.fromEntries(form));rememberDrafts();state.caseId=c.id;state.sampleId=null;state.page=0;state.evidence=[];html('#evidenceList','');await refreshData();toast('Case 已创建')})}
function newEvidence(){const sample=selectedSample();if(!sample)return toast('请先选择样本');const caseId=state.caseId;openEditor('登记人工证据',field('subject','主题')+field('claim','记录说明','',true)+field('artifacts','引用（每行一条，可留空）','',true),async form=>{await post('/api/evidence',{case_id:caseId,sample_id:sample.id,subject:form.get('subject'),claim:form.get('claim'),artifacts:String(form.get('artifacts')).split('\n').map(x=>x.trim()).filter(Boolean)});await refreshData();toast('证据已登记，等待人工复核')});$('[name="artifacts"]').required=false}
async function review(button){const id=button.dataset.id,caseId=state.caseId,note=$$('[data-review-note]').find(x=>x.dataset.reviewNote===id)?.value.trim();if(!note)return toast('请填写人工复核备注');await action(`review/${id}`,async()=>{const buttons=$$(`[data-id="${id}"]`);buttons.forEach(b=>b.disabled=true);try{await post(`/api/evidence/${encodeURIComponent(id)}/review`,{case_id:caseId,status:button.dataset.review,note});state.drafts.delete(`${caseId}/${id}`);await refreshData();toast(`复核成功，已写入审计链：${id}`)}finally{buttons.forEach(b=>b.disabled=false)}})}
async function downloadExisting(id){const r=await fetch(`/api/reports/${encodeURIComponent(id)}/download`);if(!r.ok)throw new Error((await r.json()).error);const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=/filename="([^"]+)"/.exec(r.headers.get('Content-Disposition')||'')?.[1]||id;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已下载证据快照')}
async function downloadReport(format){if(!state.api||!state.caseId)return toast('请连接 API 并选择 Case');await action('report',async()=>{const r=await post('/api/reports',{case_id:state.caseId,format});await refreshData();await downloadExisting(r.id)})}
async function send(){const input=$('#input'),message=input.value.trim(),caseId=state.caseId;if(!message)return;await action('send',async()=>{const result=await post($('#copilotMode')?.value==='provider'?'/api/copilot/complete':'/api/copilot/messages',{case_id:caseId,sample_id:selectedSample()?.id||null,message,skill_ids:$('#copilotSkill')?.value?[$('#copilotSkill').value]:[]});if(input.value.trim()===message)input.value='';await refreshData();const box=$('#messages');box.scrollTop=box.scrollHeight;if(result.job){view('analysis');toast('主 Agent 已启动，可在分析页查看和停止')}})}
async function loadSettings(){try{const r=await api('/api/settings');state.settings=r;$('#settingsJson').value=JSON.stringify(r.config,null,2);put('#settingsStatus',`配置版本 1 · 修订 ${r.revision} · 配置已加载`);renderPlaybooks();if(typeof renderIntegrationSettings==='function')await renderIntegrationSettings()}catch(e){put('#settingsStatus',e.message)}}
async function saveSettings(config){if(!state.settings)throw new Error('请先加载配置');const r=await post('/api/settings',{revision:state.settings.revision,config});state.settings={...state.settings,...r};$('#settingsJson').value=JSON.stringify(r.config,null,2);put('#settingsStatus',`已保存修订 ${r.revision}；连接状态以测试结果为准`);renderPlaybooks();if(typeof renderIntegrationSettings==='function')await renderIntegrationSettings()}
function renderPlaybooks(){html('#playbooks',(state.settings?.config.playbooks||[]).map(p=>`<article><h3>${escapeHTML(p.name)}</h3><p>${p.steps.length} 个已保存步骤 · 人工流程定义</p><button data-playbook="${escapeHTML(p.id)}">查看 / 编辑</button><button data-delete-playbook="${escapeHTML(p.id)}">删除</button></article>`).join('')||'<p>暂无已保存的 Playbook。</p>')}
async function editPlaybook(id){await loadSettings();if(!state.settings)return;const p=state.settings.config.playbooks.find(x=>x.id===id);openEditor('Playbook 定义',field('name','名称',p?.name)+field('steps','步骤（每行一项，仅保存文本）',p?.steps.join('\n'),true),async form=>{const config=structuredClone(state.settings.config),item={id:p?.id||`playbook_${Date.now()}`,name:form.get('name'),steps:String(form.get('steps')).split('\n').map(x=>x.trim()).filter(Boolean),skill_ids:p?.skill_ids||[]};config.playbooks=config.playbooks.filter(x=>x.id!==item.id);config.playbooks.push(item);await saveSettings(config)})}
// Edges represent persisted references, never inferred causality.
function graphModel(){
 const all=state.evidence.filter(inCase).filter(e=>!state.filter||e.status===state.filter),evidence=all.slice(state.page*20,state.page*20+20),eids=new Set(evidence.map(e=>e.id));
 const jobs=state.jobs.filter(inCase).filter(j=>eids.has(j.evidence_id)||evidence.some(e=>e.job_id===j.id));
 if(!all.length)jobs.push(...state.jobs.filter(inCase).slice(0,20));
 jobs.sort((a,b)=>evidence.findIndex(e=>e.id===a.evidence_id)-evidence.findIndex(e=>e.id===b.evidence_id));
 const sampleIds=new Set([...evidence,...jobs].map(x=>x.sample_id)),samples=state.samples.filter(inCase).filter(s=>sampleIds.has(s.id)||(!sampleIds.size&&s.id===selectedSample()?.id));
 const nodes=[...samples.map(record=>({record,column:0})),...jobs.map(record=>({record,column:1})),...evidence.map(record=>({record,column:2}))],ids=new Set(nodes.map(n=>n.record.id)),edges=[];
 for(const j of jobs){if(ids.has(j.sample_id))edges.push([j.sample_id,j.id,'任务输入']);if(ids.has(j.evidence_id))edges.push([j.id,j.evidence_id,'输出证据'])}
 for(const e of evidence)if(ids.has(e.sample_id))edges.push([e.sample_id,e.id,'样本引用']);return{nodes,edges};
}
function graphLayout(){
 if(!state.layouts.has(state.caseId)){let saved=null;try{saved=JSON.parse(localStorage.getItem('reverseai.graph.'+state.caseId)||'null')}catch(_){}const positions={};for(const [id,p] of Object.entries(saved?.positions||{})){if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&Math.abs(p.x)<100000&&Math.abs(p.y)<100000)positions[id]={x:p.x,y:p.y}}state.layouts.set(state.caseId,{positions,x:0,y:0,scale:1})}return state.layouts.get(state.caseId);
}
function saveGraphLayout(){try{localStorage.setItem('reverseai.graph.'+state.caseId,JSON.stringify({positions:graphLayout().positions}))}catch(_){}}
function renderGraph(){if(!$('#graphbox'))return;const model=graphModel(),l=graphLayout(),rows=[0,0,0];for(const n of model.nodes){const row=rows[n.column]++;l.positions[n.record.id]??={x:30+n.column*280,y:30+row*155}}put('#graphSample',`${model.nodes.length} 个记录 · ${model.edges.length} 个已知引用（演示记录单独标记）`);html('#graphNodes',model.nodes.map(({record:r})=>{const p=l.positions[r.id];return `<button class="record-node" data-node="${escapeHTML(r.id)}" style="left:${p.x}px;top:${p.y}px"><b>${escapeHTML(r.name||r.subject||r.type)}</b><small>${escapeHTML(provenance(r))} · ${escapeHTML(r.status||'元数据')}</small><small>${r.confidence==null?'未评分':escapeHTML(r.confidence)} · ${escapeHTML(r.id)}</small></button>`}).join('')||'<p>暂无记录，登记样本和证据后显示关系。</p>');updateGraphEdges(model);transformGraph()}
function updateGraphEdges(model=graphModel()){
  const l=graphLayout();let overlaps=0;
  html('#graphEdges','<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 Z" fill="currentColor"/></marker></defs>'+model.edges.map(([a,b,label])=>{
    const p=l.positions[a],q=l.positions[b];if(!p||!q)return '';
    const obstacles=model.nodes.filter(n=>n.record.id!==a&&n.record.id!==b).map(n=>l.positions[n.record.id]);
    const route=EvidenceRouting.route(p,q,obstacles);if(route.overlap)overlaps++;
    return route.path?`<path d="${route.path}" fill="none" marker-end="url(#arrow)"><title>${escapeHTML(label)}: ${escapeHTML(a)} → ${escapeHTML(b)}</title></path>`:'';
  }).join(''));
  put('#graphSample',`${model.nodes.length} 个当前页关联记录 · ${model.edges.length} 个已知引用${overlaps?' · '+overlaps+' 条连线因节点重叠暂不显示，请拖开节点':''}`);
}
function transformGraph(){const l=graphLayout(),world=$('#graphworld');if(world)world.style.transform=`translate(${l.x}px,${l.y}px) scale(${l.scale})`}
function fitGraph(){
 const box=$('#graphbox'),model=graphModel(),l=graphLayout();if(!model.nodes.length)return;
 const bounds=model.nodes.flatMap(n=>{const p=l.positions[n.record.id];return [p,{x:p.x+220,y:p.y+120}]});
 for(const [a,b] of model.edges){const route=EvidenceRouting.route(l.positions[a],l.positions[b],model.nodes.filter(n=>n.record.id!==a&&n.record.id!==b).map(n=>l.positions[n.record.id]));bounds.push(...route.points)}
 const minX=Math.min(...bounds.map(p=>p.x)),minY=Math.min(...bounds.map(p=>p.y)),width=Math.max(...bounds.map(p=>p.x))-minX,height=Math.max(...bounds.map(p=>p.y))-minY;
 l.scale=Math.min(1,(box.clientWidth-48)/width,(box.clientHeight-48)/height);l.x=24-minX*l.scale;l.y=24-minY*l.scale;transformGraph();
}
function showRecord(id){const r=[...state.evidence,...state.samples,...state.jobs].find(x=>inCase(x)&&x.id===id);if(!r)return;const index=state.evidence.filter(inCase).findIndex(x=>x.id===id);if(index>=0){state.filter='';if($('#evidenceFilter'))$('#evidenceFilter').value='';state.page=Math.floor(index/20);renderEvidence()}const l=graphLayout(),p=l.positions[id];if(p){l.scale=1;l.x=20-p.x;l.y=20-p.y;transformGraph()}openEditor('原始记录',`<pre>${escapeHTML(JSON.stringify(r,null,2))}</pre>`,null)}
function bindGraph(){const box=$('#graphbox');if(!box)return;let drag=null;box.onpointerdown=e=>{if(e.button!==0)return;const node=e.target.closest('[data-node]'),l=graphLayout();drag={id:node?.dataset.node,x:e.clientX,y:e.clientY,px:node?l.positions[node.dataset.node].x:l.x,py:node?l.positions[node.dataset.node].y:l.y};(node||box).setPointerCapture(e.pointerId);e.preventDefault()};box.onpointermove=e=>{if(!drag)return;const l=graphLayout(),dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.id){const p=l.positions[drag.id];p.x=drag.px+dx/l.scale;p.y=drag.py+dy/l.scale;const n=$$('[data-node]').find(n=>n.dataset.node===drag.id);n.style.left=`${p.x}px`;n.style.top=`${p.y}px`;updateGraphEdges()}else{l.x=drag.px+dx;l.y=drag.py+dy;transformGraph()}};box.onpointerup=box.onpointercancel=()=>{drag=null;saveGraphLayout()};box.ondblclick=e=>{const n=e.target.closest('[data-node]');if(n)showRecord(n.dataset.node)};box.onkeydown=e=>{const n=e.target.closest('[data-node]');if(n&&e.key==='Enter')showRecord(n.dataset.node)}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view)view(b.dataset.view);if(b.dataset.target)view(b.dataset.target);if(b.dataset.sample){state.sampleId=b.dataset.sample;renderAll()}if(b.dataset.review)review(b);if(b.dataset.record)showRecord(b.dataset.record);if(b.dataset.download)action('download',()=>downloadExisting(b.dataset.download));if(b.dataset.cancelJob)action('cancel',async()=>{await post(`/api/analysis/jobs/${b.dataset.cancelJob}/cancel`,{case_id:state.caseId});await refreshData()});if(b.dataset.flow)b.dataset.flow==='report'?downloadReport('html'):start(b.dataset.flow==='android'?'android_analysis':'static_triage');if(b.dataset.prompt){$('#input').value=b.dataset.prompt;send()}if(b.dataset.playbook)editPlaybook(b.dataset.playbook);if(b.dataset.deletePlaybook)action('playbook',async()=>{const c=structuredClone(state.settings.config);c.playbooks=c.playbooks.filter(p=>p.id!==b.dataset.deletePlaybook);await saveSettings(c)});if(b.dataset.graph){const l=graphLayout();if(b.dataset.graph==='reset'){try{localStorage.removeItem('reverseai.graph.'+state.caseId)}catch(_){}state.layouts.delete(state.caseId);renderGraph();fitGraph()}else if(b.dataset.graph==='fit')fitGraph();else{l.scale=Math.max(.05,Math.min(3,l.scale*(b.dataset.graph==='in'?1.2:1/1.2)));transformGraph()}}});const on=(id,event,fn)=>{if($(id))$(id)[event]=fn};
for(const id of ['#import','#import2','#pickSamples'])on(id,'onclick',()=>$('#files').click());on('#files','onchange',async e=>{await registerSamples([...e.target.files]);e.target.value=''});const drop=$('#dropzone');if(drop){drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');registerSamples([...e.dataTransfer.files])}}
on('#caseSelect','onchange',async e=>{rememberDrafts();state.epoch++;state.caseId=e.target.value;state.sampleId=null;state.page=0;state.evidence=[];state.filter='';$('#evidenceFilter').value='';html('#evidenceList','');renderAll();await refreshData()});on('#newCase','onclick',newCase);on('#addEvidence','onclick',newEvidence);on('#metadataCheck','onclick',()=>start('metadata_check'));for(const id of ['#run','#run2'])on(id,'onclick',()=>start());on('#theme','onclick',()=>document.documentElement.classList.toggle('light'));on('#toggleCopilot','onclick',()=>document.body.classList.toggle('copilot-open'));on('#editorCancel','onclick',()=>$('#editor').close());on('#evidenceFilter','onchange',e=>{state.filter=e.target.value;state.page=0;renderEvidence()});on('#evidencePrev','onclick',()=>{state.page--;renderEvidence()});on('#evidenceNext','onclick',()=>{state.page++;renderEvidence()});on('#send','onclick',send);on('#input','onkeydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$$('.reports>button').forEach(b=>b.onclick=()=>downloadReport($('span',b).textContent.toLowerCase()));on('#evidence .heading .primary','onclick',()=>downloadReport('json'));on('#saveSettings','onclick',()=>action('settings',()=>saveSettings(JSON.parse($('#settingsJson').value))));on('#resetSettings','onclick',()=>openEditor('恢复全部集成模板','<p>将替换 Provider、MCP、Skill、worker、子 Agent 和 Playbook 配置；不会修改 Case、样本、证据或报告。</p>',async()=>saveSettings(state.settings.defaults)));on('#newPlaybook','onclick',()=>editPlaybook());bindGraph()}
async function hydrate(){bind();renderAll();await refreshData();await loadSettings();clearInterval(window.refreshTimer);window.refreshTimer=setInterval(()=>{if(!document.hidden&&!document.activeElement?.matches('textarea,input,select')&&!$('#editor')?.open)refreshData()},2500)}
hydrate();
